name: General Issue
description: Report a bug or problem with EMC & FE +++
body:
  - type: markdown
    attributes:
      value: "*在报告问题之前，应该先使用搜索功能。同时也要看看已关闭的问题！*"
  - type: textarea
    attributes:
      label: "议题描述"
      description: "对问题的清晰简明描述，以及在适当情况下应有的预期结果。"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "复现步骤"
      description: "如果有具体步骤来重现该问题，请在此列出。"
      placeholder: |
        1. 首先...
        2. 接下来...
        3. 结果...
  - type: input
    attributes:
      label: "整合包版本"
      description: "你使用的是哪个整合包版本？"
      placeholder: e.g. 2.0.0-Pre.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: "添加的模组版本"
      description: "如果你添加了其它模组，请在这里列出它们的版本。"
  - type: input
    attributes:
      label: "（崩溃）日志链接"
      description: "请在此提供一个 [gist](https://gist.github.com/) / [mclo.gs](https://mclo.gs/) / 其它链接。"