onCull = true
MaxEntityEntities = 256
qualityModes = "NORMAL"
RenderWeather = "LOW"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
BlackTagListEntity = []
WhiteTagListEntity = []
isAlwaysShowItemCount = true
startTime = 173.667
Hud = false
HudRXTX = false
HudFPS = false
HudCPU = false
HudGPU = false
HudRAM = false
HudEntityCount = false
HudPlayerPos = false
HudServer = false
HudCameraTarget = false
Mood = false
MaxParticleDistance = 128
WhiteListedParticle = []
BlackListedParticle = []
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 488
GuiY = 0
UseAui = false
DeBug = true
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 1
GuiViewMode = "TECHNICAL"
MinDistance = 5
EntityDistance = 64
TickPerformance = false
ParticlePerformance = false
EntityViewDebug = false
ParticleCountLimit = 16384
BlockBreakParticle = true
AsyncCompute = false
