onCull = true
MaxEntityEntities = 256
EntitiesDistance = 128
qualityModes = "normal"
RenderWeather = "normal"
RenderTNTExplosions = true
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
startTime = 224.588
chatFix = false
onGui = true
GuiRXTX = false
GuiFPS = true
GuiCPU = false
GuiGPU = true
GuiRAM = true
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = false
GuiCameraTarget = false
Mood = false
Particle = true
BlockBreakParticleMode = "normal"
MaxParticleDistance = 128
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = true
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 488
GuiY = 0
EntityRender = true
UseVanillaGui = false
DeBug = false
TextBackground = false
