onCull = true
MaxEntityEntities = 128
EntitiesDistance = 64
qualityModes = "normal"
RenderWeather = "normal"
RenderTNTExplosions = true
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
startTime = 149.654
chatFix = false
onGui = true
GuiRXTX = false
GuiFPS = true
GuiCPU = false
GuiGPU = true
GuiRAM = true
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = false
GuiCameraTarget = false
Mood = false
Particle = true
BlockBreakParticleMode = "high"
MaxParticleDistance = 128
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = true
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 250
GuiY = 5
EntityRender = true
UseVanillaGui = false
DeBug = false
TextBackground = false
